'use strict';
const $=id=>document.getElementById(id);
let currentPlan=null;
function node(tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e;}
async function api(path,body){const response=await fetch('/api/rag'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-SAP-CUA':'workbench'},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(typeof result.detail==='string'?result.detail:JSON.stringify(result.detail));return result;}
function message(text,error=false){$('message').textContent=text;$('message').className=error?'failed':'';}
function showSources(hits){$('sources').replaceChildren();if(!hits.length){$('sources').append(node('p','No matching knowledge.'));return;}for(const hit of hits){const card=node('article','','source-card');card.append(node('strong',hit.title),node('p',hit.content),node('small',`${hit.collection} · ${hit.source} · ${hit.source_version} · score ${Number(hit.rerank_score).toFixed(2)}`));$('sources').append(card);}}
function showRun(run){$('result-badge').textContent=run.status.toUpperCase();$('trace').replaceChildren();for(const [i,step] of (run.steps||[]).entries()){const row=node('div','','step');const body=node('div','');row.append(node('b',String(i+1).padStart(2,'0')),body);body.append(node('strong',step.action.action),node('small',`${step.executor} · ${step.verification.success?'verified':'failed'}${step.recovery.length?' · recovered after '+step.recovery.length+' attempt(s)':''}`));$('trace').append(row);}$('evidence').textContent=JSON.stringify(run,null,2);if(run.error)$('trace').append(node('p',run.error,'failed'));}
async function refresh(){const runs=await api('/runs');$('history').replaceChildren();if(!runs.length)$('history').append(node('p','No runs yet.'));for(const run of runs){const row=node('div','','history-row');row.append(node('span',run.instruction),node('small',run.status));const b=node('button','Inspect','secondary');b.addEventListener('click',()=>showRun(run));row.append(b);$('history').append(row);}}
async function status(){const s=await api('/status');$('knowledge-status').textContent=Object.values(s.collections).reduce((a,b)=>a+b,0)+' knowledge versions';$('scope-status').textContent=s.scope.customer+' / '+s.scope.tenant;$('capabilities').replaceChildren();for(const [key,value]of Object.entries({Store:s.backend,Embedding:s.embedding,Reranker:s.reranker,Training:'Not required',Execution:'Local sandbox; live SAP disabled'}))$('capabilities').append(node('dt',key),node('dd',value));}
$('plan-button').addEventListener('click',async()=>{const button=$('plan-button');button.disabled=true;$('execute').disabled=true;currentPlan=null;message('Retrieving knowledge and compiling the plan…');try{const plan=await api('/plans',{requirement:$('requirement').value});currentPlan=plan;$('plan-json').textContent=JSON.stringify(plan,null,2);$('plan-summary').replaceChildren();for(const step of plan.steps)$('plan-summary').append(node('div',`${step.id}  ${step.action}  → ${step.preferred_executor}`,'plan-step'));for(const blocker of plan.blockers)$('plan-summary').append(node('p',blocker,'failed'));$('execute').disabled=plan.blockers.length>0;$('plan-note').textContent=plan.steps.length+' actions · '+plan.sources.length+' retrieved sources';showSources(plan.sources);message(plan.blockers.length?'This plan needs additional configuration.':'Plan ready. Execution uses a fresh sandbox.');await refresh();}catch(e){message(e.message,true);}finally{button.disabled=false;}});
$('execute').addEventListener('click',async()=>{if(!currentPlan)return;$('execute').disabled=true;$('plan-button').disabled=true;message('Executing and verifying each step…');try{const run=await api('/plans/'+currentPlan.id+'/run',{});showRun(run);message(run.success?'Sandbox verified'+(run.knowledge_ingested?' · trajectory added to knowledge.':'.'):run.error,!run.success);await Promise.all([refresh(),status()]);}catch(e){message(e.message,true);}finally{currentPlan=null;$('plan-button').disabled=false;}});
$('load-example').addEventListener('click',()=>{$('requirement').value='Create HTTPS → Content Modifier → Router → OData V4 with error handling.';});
$('search-form').addEventListener('submit',async event=>{event.preventDefault();try{showSources((await api('/search',{query:$('query').value})).hits);}catch(e){message(e.message,true);}});
$('refresh').addEventListener('click',()=>refresh().catch(e=>message(e.message,true)));
Promise.all([status(),refresh()]).catch(e=>{$('knowledge-status').textContent='Setup required';message(e.message,true);});

function invalidatePlan(){currentPlan=null;$('execute').disabled=true;$('plan-note').textContent='Generate a new plan for this requirement.';}
$('requirement').addEventListener('input',invalidatePlan);
$('load-example').addEventListener('click',invalidatePlan);

async function sapApi(path,body){const response=await fetch('/api/sap'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-SAP-CUA':'workbench'},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(typeof result.detail==='string'?result.detail:'Connection check failed');return result;}
function showConnection(s){$('sap-badge').textContent=s.configured?'CONFIGURED · UNVALIDATED':'SETUP REQUIRED';$('sap-probe').disabled=!s.configured;$('sap-setup').textContent=s.configured?'Configured host: '+s.tenant_host+'. Check read access to continue.':'Configure '+[...s.missing,...s.invalid].join(', ')+' in the project’s ignored .env file, then restart the app. Keep secret values out of chat.';const probe=s.last_probe||s;if(probe.checks){$('sap-checks').replaceChildren();for(const check of probe.checks)$('sap-checks').append(node('div',check.resource+' · '+(check.success?'read access confirmed':check.reason)+(check.status_code?' · HTTP '+check.status_code:''),'connection-check'));if(probe.success)$('sap-badge').textContent='READ ACCESS CONFIRMED';else if(probe.checks.length)$('sap-badge').textContent='CHECK NEEDS ATTENTION';}}
$('sap-probe').addEventListener('click',async()=>{$('sap-probe').disabled=true;$('sap-setup').textContent='Checking read access…';try{showConnection(await sapApi('/probe',{}));}catch(e){$('sap-setup').textContent=e.message;}finally{$('sap-probe').disabled=false;}});
sapApi('/status').then(showConnection).catch(e=>{$('sap-setup').textContent=e.message;});
